// Benchmark "b06_C.blif" written by ABC on Sat Jul 06 16:19:01 2024

module b06_C.blif ( 
    ACKOUT_REG_SCAN_IN, CONT_EQL, STATE_REG_2__SCAN_IN,
    STATE_REG_1__SCAN_IN, STATE_REG_0__SCAN_IN, CC_MUX_REG_2__SCAN_IN,
    CC_MUX_REG_1__SCAN_IN, USCITE_REG_2__SCAN_IN, USCITE_REG_1__SCAN_IN,
    ENABLE_COUNT_REG_SCAN_IN,
    CC_MUX_2_, CC_MUX_1_, USCITE_2_, USCITE_1_, ENABLE_COUNT, ACKOUT,
    STATE_REG_2__SCAN_OUT, STATE_REG_1__SCAN_OUT, STATE_REG_0__SCAN_OUT,
    CC_MUX_REG_2__SCAN_OUT, CC_MUX_REG_1__SCAN_OUT, USCITE_REG_2__SCAN_OUT,
    ENABLE_COUNT_REG_SCAN_OUT, ACKOUT_REG_SCAN_OUT  );
  input  ACKOUT_REG_SCAN_IN, CONT_EQL, STATE_REG_2__SCAN_IN,
    STATE_REG_1__SCAN_IN, STATE_REG_0__SCAN_IN, CC_MUX_REG_2__SCAN_IN,
    CC_MUX_REG_1__SCAN_IN, USCITE_REG_2__SCAN_IN, USCITE_REG_1__SCAN_IN,
    ENABLE_COUNT_REG_SCAN_IN;
  output CC_MUX_2_, CC_MUX_1_, USCITE_2_, USCITE_1_, ENABLE_COUNT, ACKOUT,
    STATE_REG_2__SCAN_OUT, STATE_REG_1__SCAN_OUT, STATE_REG_0__SCAN_OUT,
    CC_MUX_REG_2__SCAN_OUT, CC_MUX_REG_1__SCAN_OUT, USCITE_REG_2__SCAN_OUT,
    ENABLE_COUNT_REG_SCAN_OUT, ACKOUT_REG_SCAN_OUT;
  wire n25, n26, n28, n29, n31, n32, n35, n38;
  INV_X1    g00(.A(STATE_REG_2__SCAN_IN), .ZN(n25));
  OR2_X1    g01(.A1(STATE_REG_0__SCAN_IN), .A2(STATE_REG_1__SCAN_IN), .ZN(n26));
  NOR2_X1   g02(.A1(n26), .A2(n25), .ZN(USCITE_REG_2__SCAN_OUT));
  INV_X1    g03(.A(STATE_REG_0__SCAN_IN), .ZN(n28));
  NOR3_X1   g04(.A1(n28), .A2(STATE_REG_1__SCAN_IN), .A3(STATE_REG_2__SCAN_IN), .ZN(n29));
  OR2_X1    g05(.A1(n29), .A2(USCITE_REG_2__SCAN_OUT), .ZN(STATE_REG_2__SCAN_OUT));
  INV_X1    g06(.A(STATE_REG_1__SCAN_IN), .ZN(n31));
  OR2_X1    g07(.A1(STATE_REG_0__SCAN_IN), .A2(STATE_REG_2__SCAN_IN), .ZN(n32));
  OAI22_X1  g08(.A1(n26), .A2(n25), .B1(n31), .B2(n32), .ZN(STATE_REG_1__SCAN_OUT));
  NAND3_X1  g09(.A1(n28), .A2(n31), .A3(STATE_REG_2__SCAN_IN), .ZN(STATE_REG_0__SCAN_OUT));
  AOI21_X1  g10(.A(STATE_REG_1__SCAN_IN), .B1(STATE_REG_0__SCAN_IN), .B2(STATE_REG_2__SCAN_IN), .ZN(n35));
  NAND2_X1  g11(.A1(n35), .A2(n32), .ZN(CC_MUX_REG_1__SCAN_OUT));
  AND3_X1   g13(.A1(STATE_REG_0__SCAN_IN), .A2(STATE_REG_1__SCAN_IN), .A3(STATE_REG_2__SCAN_IN), .ZN(n38));
  OAI22_X1  g14(.A1(n32), .A2(n31), .B1(CONT_EQL), .B2(n38), .ZN(ENABLE_COUNT_REG_SCAN_OUT));
  BUF_X1    g15(.A(CC_MUX_REG_2__SCAN_IN), .Z(CC_MUX_2_));
  BUF_X1    g16(.A(CC_MUX_REG_1__SCAN_IN), .Z(CC_MUX_1_));
  BUF_X1    g17(.A(USCITE_REG_2__SCAN_IN), .Z(USCITE_2_));
  BUF_X1    g18(.A(USCITE_REG_1__SCAN_IN), .Z(USCITE_1_));
  BUF_X1    g19(.A(ENABLE_COUNT_REG_SCAN_IN), .Z(ENABLE_COUNT));
  BUF_X1    g20(.A(ACKOUT_REG_SCAN_IN), .Z(ACKOUT));
  OR2_X1    g21(.A1(n29), .A2(USCITE_REG_2__SCAN_OUT), .ZN(CC_MUX_REG_2__SCAN_OUT));
  OAI22_X1  g22(.A1(n32), .A2(n31), .B1(CONT_EQL), .B2(n38), .ZN(ACKOUT_REG_SCAN_OUT));
endmodule


